DECLARE @MACTL BIGINT = 16
DECLARE @MACH BIGINT = 1
DECLARE @Return NVARCHAR(500)

EXEC sp_CapNhatCauTraLoiSangCauHoiKhac_DEMO @MACTL, @MACH, @Return out
print @Return

SELECT * FROM CAUTRALOI 
SELECT * FROM CAUHOI