DECLARE @MACH BIGINT = 2
DECLARE @SOCAUHOI INT = 2
DECLARE @THANGDIEM FLOAT = 0.5
DECLARE @MUCDO INT = 2
DECLARE @Return nvarchar(500)

EXEC sp_CapNhatSoLuongCauHoi @MACH, @SOCAUHOI, @THANGDIEM, @MUCDO, @Return out 