CREATE PROC sp_CapNhatThongTin
@MaND bigint,
@HoTen nvarchar(255),
@TenDangNhap varchar(30),
@ToanQuyenGV bit,
@TrangThai bit,
@MaLoai bigint,
@MaBM bigint,
@MaGVQL bigint,
@Return int out
AS
BEGIN TRAN
	BEGIN TRY
		SET @Return = -1;
		IF NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAND] = @MaND)
			BEGIN
				PRINT N'MA NGUOI DUNG KHONG TON TAI'
				SET @Return = 1
			END
		ELSE IF NOT EXISTS(SELECT * FROM LOAINGUOIDUNG WHERE [MALOAI] = @MaLoai)
			BEGIN
				PRINT N'MA lOAI NGUOI DUNG KHONG TON TAI'
				SET @Return = 2
			END
		ELSE IF NOT EXISTS(SELECT * FROM BOMON WHERE [MABM] = @MaBM)
			BEGIN
				PRINT N'MA BO MON KHONG TON TAI'
				SET @Return = 3
			END
		WAITFOR DELAY '00:00:05'	
		IF @Return = -1
			BEGIN
				UPDATE [NGUOIDUNG] SET TENDANGNHAP = @TenDangNhap,HOTEN = @HoTen, TRANGTHAI = @TrangThai, TOANQUYENGV = @ToanQuyenGV, MALOAI = @MaLoai, MABM = @MaBM, MAGVQL = @MaGVQL  WHERE [MAND] = @MaND
				SET @Return = 0;
			END
	END TRY
	BEGIN CATCH
		PRINT N'LOI HE THONG'
		SET @Return = 4
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN
GO

CREATE PROC sp_ThayDoiGVQL
@MaND bigint,
@MaGVQL bigint,
@Return int out
AS
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAND] = @MaND)
		BEGIN
			PRINT N'MA NGUOI DUNG KHONG TON TAI'
			SET @Return = 1
		END
	IF NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAND] = @MaGVQL)
		BEGIN
			PRINT N'MA GVQL KHONG TON TAI'
			SET @Return = 2
		END
	UPDATE [NGUOIDUNG] SET MAGVQL = @MaGVQL  WHERE [MAND] = @MaND
	SET @Return = 0
	END TRY
	BEGIN CATCH
		PRINT N'LOI HE THONG'
		ROLLBACK TRAN
		SET @Return = 3
	END CATCH
COMMIT TRAN
GO