USE [QuanLyCauHoiTracNghiem]

IF OBJECT_ID('sp_LayDanhSachBoMon') IS NOT NULL
	DROP PROC sp_LayDanhSachBoMon
GO
CREATE PROCEDURE sp_LayDanhSachBoMon
AS
BEGIN
	BEGIN TRAN
		BEGIN TRY
			SELECT * FROM BOMON
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN
		END CATCH
	COMMIT TRAN
END
GO