IF OBJECT_ID('sp_LayDanhSachMonHoc') IS NOT NULL
	DROP PROC sp_LayDanhSachMonHoc
GO

CREATE PROCEDURE sp_LayDanhSachMonHoc
	@TENMH NVARCHAR(MAX),
	@MABM BIGINT
AS
BEGIN
	BEGIN TRAN
		BEGIN TRY
			IF @MABM = 0 AND @TENMH = 'ALL'
			BEGIN
				PRINT 'Tìm kiếm tất cả'
				SELECT MH.MAMH, MH.TENMH, MH.MABM, BM.TENBM FROM MONHOC MH, BOMON BM WHERE BM.MABM = MH.MABM
			END
			ELSE IF @TENMH  = 'ALL'
			BEGIN
				PRINT 'Tìm kiếm theo bộ môn'
				SELECT MH.MAMH, MH.TENMH, MH.MABM, BM.TENBM FROM MONHOC MH, BOMON BM WHERE BM.MABM = MH.MABM AND @MABM = MH.MABM
			END
			ELSE IF @MABM = 0
			BEGIN
				PRINT 'Tìm kiếm theo tên môn học'
				SELECT MH.MAMH, MH.TENMH, MH.MABM, BM.TENBM FROM MONHOC MH, BOMON BM WHERE BM.MABM = MH.MABM AND MH.TENMH LIKE '%'+@TENMH+'%'
			END
			ELSE
			BEGIN
				PRINT 'Tìm kiếm theo bộ môn và tên môn học'
				PRINT @MABM
				SELECT MH.MAMH, MH.TENMH, MH.MABM, BM.TENBM FROM MONHOC MH, BOMON BM WHERE BM.MABM = MH.MABM AND @MABM = MH.MABM AND MH.TENMH LIKE '%'+@TENMH+'%'
			END
		END TRY
		BEGIN CATCH
			PRINT N'XẢY RA LỖI'
			ROLLBACK TRAN
		END CATCH
	COMMIT TRAN
END
GO