USE [QuanLyCauHoiTracNghiem]

IF OBJECT_ID('sp_XoaMonHoc') IS NOT NULL
	DROP PROC sp_XoaMonHoc
GO
CREATE PROC sp_XoaMonHoc
	@MAMH BIGINT,
	@KETQUA INT OUTPUT
AS BEGIN
	BEGIN TRAN
		BEGIN TRY
			DECLARE @IS_EXIST_BM BIT = (SELECT 1 FROM MONHOC WHERE @MAMH = MONHOC.MAMH)

			IF @IS_EXIST_BM!=1
			BEGIN 
				ROLLBACK TRAN
				SET @KETQUA = 2 -- Môn học không tồn tại  
			END

			DELETE FROM MONHOC WHERE MAMH = @MAMH
			SET @KETQUA = 1
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN
			SET @KETQUA = 0 --Thất bại
		END CATCH
	COMMIT TRAN
END
GO 