
CREATE PROC SP_LOAD_DSGV_CUNG_GVQL_FIX
	@MAGVQL BIGINT
AS
SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN
	BEGIN TRAN
		BEGIN TRY
			IF NOT EXISTS(SELECT *
							FROM NGUOIDUNG ND
							WHERE ND.MAND = @MAGVQL AND
									ND.MALOAI = 2) -- 2: GVQL)
			BEGIN
				ROLLBACK TRAN
				RETURN 0
			END
			
			DECLARE @COUNT INT = (SELECT COUNT(*) FROM NGUOIDUNG WHERE MAGVQL = @MAGVQL)
			PRINT 'CO ' + CAST(@COUNT AS VARCHAR(10)) + ' GV THUOC CUNG GVQL LA ' + CAST(@MAGVQL AS VARCHAR(10)) + ' :'
			WAITFOR DELAY '0:0:10'
			SELECT * FROM NGUOIDUNG WHERE MAGVQL = @MAGVQL
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN
			RETURN 0
		END CATCH
	COMMIT TRAN
	RETURN 1
END
GO

CREATE PROC SP_UPDATEGVQL_FIX
	@MAGV BIGINT,
	@MAGVQL BIGINT
AS
BEGIN
	BEGIN TRAN
		BEGIN TRY
			IF NOT EXISTS (SELECT *
							FROM NGUOIDUNG ND
							WHERE ND.MAND = @MAGVQL AND
									ND.MALOAI = 2) -- 2: GVQL
			BEGIN
				ROLLBACK TRAN
				RETURN 0
			END

			UPDATE NGUOIDUNG
			SET MAGVQL = @MAGVQL
			WHERE MAND = @MAGV

			RETURN 1
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN
			RETURN 0
		END CATCH
	COMMIT TRAN
END
GO