USE [QuanLyCauHoiTracNghiem]


IF OBJECT_ID('sp_CapNhatMonHoc') IS NOT NULL
	DROP PROC sp_CapNhatMonHoc
GO
CREATE PROC sp_CapNhatMonHoc
	@MAMH BIGINT,
	@TENMH NVARCHAR(MAX),
	@MABM BIGINT,
	@KETQUA INT OUTPUT
AS 
--SET MỨC CÔ LẬP
BEGIN
	BEGIN TRAN
		BEGIN TRY
			DECLARE @IS_EXIST_MH BIT = (SELECT 1 FROM MONHOC WHERE @MAMH = MONHOC.MAMH)

			IF @IS_EXIST_MH != 1
			BEGIN 
				SET @KETQUA = 2 --Môn học này không tồn tại  
				ROLLBACK TRAN
				RETURN
			END
			
			DECLARE @IS_EXIS_BM BIT = (SELECT 1 FROM BOMON WHERE @MABM = BOMON.MABM)

			IF @IS_EXIS_BM != 1
			BEGIN 
				SET @KETQUA = 4 --Bộ môn này không tồn tại  
				ROLLBACK TRAN
				RETURN
			END

			UPDATE MONHOC SET TENMH = @TENMH, MABM = @MABM WHERE MAMH = @MAMH	
			
			WAITFOR DELAY '0:0:10' --CHỜ 10 GIÂY
					
			SET @KETQUA = 1
			IF (@TENMH LIKE '%[^a-zA-Z0-9 ._]%')
			BEGIN
				PRINT N'Tên môn học không hợp lệ'
				SET @KETQUA = 3 --Tên môn học chứa kí tự đặc biệt
				ROLLBACK TRAN
				RETURN
			END
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN
			SET @KETQUA = 0
		END CATCH
	COMMIT TRAN
END
GO 



--IF OBJECT_ID('sp_CapNhatTenMonHoc_Delay') IS NOT NULL
--	DROP PROC sp_CapNhatTenMonHoc_Delay
--GO

--CREATE PROC sp_CapNhatTenMonHoc_Delay
--	@MAMH BIGINT,
--	@TENMH NVARCHAR(255)
--AS 
----SET TRANSACTION ISOLATION LEVEL SERIALIZABLE --Xin & giữ khóa đến hết gtác
--BEGIN
--	BEGIN TRAN
--		BEGIN TRY
--			UPDATE MONHOC
--			SET TENMH = @TENMH
--			WHERE MAMH = @MAMH

--			WAITFOR DELAY '0:0:10' --chờ 10 giây

--			SELECT * FROM MONHOC WHERE MAMH = @MAMH
--		END TRY

--		BEGIN CATCH
--			ROLLBACK TRAN
--			RETURN 0
--		END CATCH
--	COMMIT TRAN
--	RETURN 1
--END
--GO

--IF OBJECT_ID('sp_CapNhatTenMonHoc') IS NOT NULL
--	DROP PROC sp_CapNhatTenMonHoc
--GO

--CREATE PROC sp_CapNhatTenMonHoc
--	@MAMH BIGINT,
--	@TENMH NVARCHAR(255)
--AS
----SET TRANSACTION ISOLATION LEVEL SERIALIZABLE --Xin & giữ khóa đến hết gtác

----SET TRAN ISOLATION LEVEL READ UNCOMMITTED

--BEGIN
--	BEGIN TRAN
--		BEGIN TRY
--			UPDATE MONHOC
--			SET TENMH = @TENMH
--			WHERE MAMH = @MAMH

--		END TRY

--		BEGIN CATCH
--			ROLLBACK TRAN
--			RETURN 0
--		END CATCH
--	COMMIT TRAN
--	RETURN 1
--END
--GO
