USE [QuanLyCauHoiTracNghiem]

IF OBJECT_ID('sp_CapNhatTenMonHoc_Delay') IS NOT NULL
	DROP PROC sp_CapNhatTenMonHoc_Delay
GO

CREATE PROC sp_CapNhatTenMonHoc_Delay
	@MAMH BIGINT,
	@TENMH NVARCHAR(255)
AS 
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE --Xin & giữ khóa đến hết gtác
BEGIN
	BEGIN TRAN
		BEGIN TRY
			UPDATE MONHOC
			SET TENMH = @TENMH
			WHERE MAMH = @MAMH

			WAITFOR DELAY '0:0:10' --chờ 10 giây

			SELECT * FROM MONHOC WHERE MAMH = @MAMH
		END TRY

		BEGIN CATCH
			ROLLBACK TRAN
			RETURN 0
		END CATCH
	COMMIT TRAN
	RETURN 1
END
GO

IF OBJECT_ID('sp_CapNhatTenMonHoc') IS NOT NULL
	DROP PROC sp_CapNhatTenMonHoc
GO

CREATE PROC sp_CapNhatTenMonHoc
	@MAMH BIGINT,
	@TENMH NVARCHAR(255)
AS
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE --Xin & giữ khóa đến hết gtác

--SET TRAN ISOLATION LEVEL READ UNCOMMITTED

BEGIN
	BEGIN TRAN
		BEGIN TRY
			UPDATE MONHOC
			SET TENMH = @TENMH
			WHERE MAMH = @MAMH

		END TRY

		BEGIN CATCH
			ROLLBACK TRAN
			RETURN 0
		END CATCH
	COMMIT TRAN
	RETURN 1
END
GO
