
CREATE PROCEDURE sp_LayDanhGV
	@MaGVQL bigint
AS
BEGIN
	BEGIN TRAN
		BEGIN TRY
			SELECT nd.*,lnd.TENLOAIND, bm.TENBM 
			FROM NGUOIDUNG nd, BOMON bm, LOAINGUOIDUNG lnd 
			WHERE nd.MABM = bm.MABM and 
					nd.MALOAI = lnd.MALOAI and 
					nd.MAGVQL = @MaGVQL
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN
		END CATCH
	COMMIT TRAN
END
GO