IF OBJECT_ID('SP_THEMMONHOC') IS NOT NULL
	DROP PROC SP_THEMMONHOC
GO
CREATE PROC SP_THEMMONHOC 
	@MABM BIGINT,
	@TENMH NVARCHAR(MAX),
	@KETQUA BIT OUTPUT
AS BEGIN
	DECLARE @ISEXIST BIT = (SELECT 1 FROM BOMON WHERE @MABM = BOMON.MABM)

	IF @ISEXIST!=1 BEGIN SET @KETQUA = 0  RETURN END

	INSERT INTO MONHOC(MABM, TENMH) VALUES (@MABM, @TENMH)
	SET @KETQUA = 1
END
GO 


INSERT INTO BOMON VALUES ('TOAN CAO CAP')
DECLARE @RES BIT
EXEC SP_THEMMONHOC 1, 'SINH', @RES

PRINT CAST(@RES AS VARCHAR(100)) 
GO