CREATE PROCEDURE sp_XuatDanhSachCauHoi @Offset int, @fetch_next int
AS
BEGIN
	BEGIN TRAN
		BEGIN TRY
SELECT * 
FROM CAUHOI
ORDER BY MaCauHoi
OFFSET @Offset ROWS FETCH NEXT @fetch_next ROWS ONLY
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN
		END CATCH
	COMMIT TRAN
END
GO