CREATE PROCEDURE sp_LayDanhSachBoDeThi
AS
BEGIN
	BEGIN TRAN
		BEGIN TRY
			SELECT B.*, M.TENMH
			FROM BODETHI B , MONHOC M 
			WHERE B.MAMH = M.MAMH; 
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN
		END CATCH
	COMMIT TRAN
END
GO