ALTER PROCEDURE sp_LayDanhSachCauTraLoiTheoCauHoi
@MACH bigint,
@Return nvarchar(500) out
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			IF NOT EXISTS ( SELECT * FROM CAUHOI WHERE @MACH = MACH )
			BEGIN
				SET @Return = N'Không tồn tại câu hỏi này'
			END

			SELECT * FROM CAUTRALOI WHERE MACH = @MACH
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		SET @Return = ERROR_MESSAGE()
		ROLLBACK TRAN
	END CATCH
END
GO