CREATE PROCEDURE sp_LayDanhSachCauHoiTheoDeThi
@MABDT bigint
AS
BEGIN
	BEGIN TRAN
		BEGIN TRY
			SELECT c.*
			FROM TAOBODETHI t , CAUHOI c 
			WHERE t.MABDT = @MABDT AND t.MACH = c.MACH 
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN
		END CATCH
	COMMIT TRAN
END
GO