USE [QuanLyCauHoiTracNghiem]

IF OBJECT_ID('sp_CapNhatMonHoc') IS NOT NULL
	DROP PROC sp_CapNhatMonHoc
GO

CREATE PROC sp_CapNhatMonHoc
	@MAMH BIGINT,
	@TENMH NVARCHAR(255)
AS
SET TRAN ISOLATION LEVEL SERIALIZABLE
--SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN
	BEGIN TRAN
		BEGIN TRY
			IF NOT EXISTS(SELECT 1 FROM MONHOC WHERE MAMH = @MAMH)
			BEGIN
				PRINT N'Môn học không tồn tại'
				ROLLBACK TRAN
			END
			WAITFOR DELAY '0:0:10'
			UPDATE MONHOC
			SET TENMH = @TENMH
			WHERE MAMH = @MAMH
		END TRY

		BEGIN CATCH
			PRINT ERROR_MESSAGE()
			ROLLBACK TRAN
		END CATCH
	COMMIT TRAN
END

GO

IF OBJECT_ID('sp_XoaMonHoc') IS NOT NULL
	DROP PROC sp_XoaMonHoc
GO

CREATE PROC sp_XoaMonHoc
	@MAMH BIGINT
AS
SET TRAN ISOLATION LEVEL SERIALIZABLE
BEGIN
	BEGIN TRAN
		BEGIN TRY
			IF NOT EXISTS(SELECT 1 FROM MONHOC WHERE MAMH = @MAMH)
			BEGIN
				PRINT N'Môn học không tồn tại'
				ROLLBACK TRAN
			END
			DELETE FROM MONHOC WHERE MAMH = @MAMH
		END TRY
		BEGIN CATCH
			PRINT ERROR_MESSAGE()
			ROLLBACK TRAN
		END CATCH
	COMMIT TRAN
END

GO