CREATE PROC sp_CapNhatThongTin
@MaND bigint,
@HoTen nvarchar(255),
@TenDangNhap varchar(30),
@MatKhau varchar(30)
AS
BEGIN
IF NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAND] = @MaND)
	BEGIN
		PRINT N'MA NGUOI DUNG KHONG TON TAI'
		RETURN 1
	END
ELSE
	BEGIN
		UPDATE [NGUOIDUNG] SET TENDANGNHAP = @TenDangNhap,HOTEN = @HoTen,MATKHAU = @MatKhau  WHERE [MAND] = @MaND
		RETURN 0
	END
END
GO