CREATE PROC sp_CapNhatThongTin
@MaND bigint,
@HoTen nvarchar(255),
@TenDangNhap varchar(30),
@MatKhau varchar(30),
@MaLoai bigint,
@MaBM bigint
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAND] = @MaND)
			BEGIN
				PRINT N'MA NGUOI DUNG KHONG TON TAI'
				ROLLBACK TRAN
				RETURN 1
			END
		ELSE IF NOT EXISTS(SELECT * FROM LOAINGUOIDUNG WHERE [MALOAI] = @MaLoai)
			BEGIN
				PRINT N'MA lOAI NGUOI DUNG KHONG TON TAI'
				ROLLBACK TRAN
				RETURN 1
			END
		ELSE IF NOT EXISTS(SELECT * FROM BOMON WHERE [MABM] = @MaBM)
			BEGIN
				PRINT N'MA BO MON KHONG TON TAI'
				ROLLBACK TRAN
				RETURN 1
			END
		UPDATE [NGUOIDUNG] SET TENDANGNHAP = @TenDangNhap,HOTEN = @HoTen,MATKHAU = @MatKhau, MALOAI = @MaLoai, MABM = @MaBM  WHERE [MAND] = @MaND
	END TRY
	BEGIN CATCH
		PRINT N'LOI HE THONG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO