CREATE PROC sp_CapNhatTrangThai
@MaND bigint,
@TrangThai bit
AS
BEGIN
IF EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAND] = @MaND)
	BEGIN
		UPDATE [NGUOIDUNG] SET [TRANGTHAI] = @TrangThai  WHERE [MAND] = @MaND
		RETURN 0
	END
ELSE
	BEGIN
		PRINT N'MA NGUOI DUNG KHONG TON TAI'
		RETURN 1
	END
END
GO