CREATE PROC sp_CapQuyenQuanLy
@MaND bigint,
@ToanQuyenGV bit
AS
BEGIN
IF EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAND] = @MaND)
	BEGIN
		UPDATE [NGUOIDUNG] SET [TOANQUYENGV] = @ToanQuyenGV  WHERE [MAND] = @MaND
		RETURN 0
	END
ELSE
	BEGIN
		PRINT N'MA NGUOI DUNG KHONG TON TAI'
		RETURN 1
	END
END
GO