CREATE PROCEDURE sp_LayDanhSachNguoiDung
AS
BEGIN
	BEGIN TRAN
		BEGIN TRY
			SELECT nd.*,lnd.TENLOAIND, bm.TENBM, nd2.HOTEN FROM NGUOIDUNG nd,NGUOIDUNG nd2,BOMON bm, LOAINGUOIDUNG lnd WHERE nd.MABM = bm.MABM and nd.MALOAI = lnd.MALOAI and (nd.MAGVQL IS NULL or nd.MAGVQL=nd2.MAND)
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN
		END CATCH
	COMMIT TRAN
END
GO