CREATE PROC sp_ThayDoiGVQL
@MaND bigint,
@MaGVQL bit
AS
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAND] = @MaND)
		BEGIN
			PRINT N'MA NGUOI DUNG KHONG TON TAI'
			ROLLBACK TRAN
			RETURN 1
		END
	ELSE IF NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAGVQL] = @MaGVQL)
		BEGIN
			PRINT N'MA GVQL KHONG TON TAI'
			ROLLBACK TRAN
			RETURN 2
		END
	UPDATE [NGUOIDUNG] SET MAGVQL = @MaGVQL  WHERE [MAND] = @MaND
	END TRY
BEGIN CATCH
	PRINT N'LOI HE THONG'
	ROLLBACK TRAN
	RETURN 1
END CATCH
COMMIT TRAN
RETURN 0
GO