CREATE PROC sp_ThemBoMon
@TenBM nvarchar(255)
AS
BEGIN TRAN
	BEGIN TRY
		INSERT INTO BOMON ([TENBM]) VALUES (@TenBM)
	END TRY
	BEGIN CATCH
		PRINT N'LOI HE THONG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO