CREATE PROC sp_XoaBoMon
@MaBM bigint,
@Return int out
AS
BEGIN TRAN
	BEGIN TRY
		SET @Return = 0
		IF NOT EXISTS(SELECT * FROM BOMON WHERE [MABM] = @MaBM)
			BEGIN
				PRINT N'MA BO MON KHONG TON TAI'
				SET @Return = 1
			END
		ELSE IF EXISTS(SELECT * FROM NGUOIDUNG WHERE [MABM] = @MaBM)
			BEGIN
				PRINT N'BO MON DA DUOC SU DUNG. KHONG THE XOA DUOC'
				SET @Return = 2
			END
		IF @Return = 0
			BEGIN
				DELETE BOMON WHERE [MABM] = @MaBM
			END
	END TRY
	BEGIN CATCH
		PRINT N'LOI HE THONG'
		SET @Return = 3
		ROLLBACK TRAN		
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO