ALTER PROC sp_ThayDoiGVQL
@MaND bigint,
@MaGVQL bigint,
@Return int out
AS
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAND] = @MaND)
		BEGIN
			PRINT N'MA NGUOI DUNG KHONG TON TAI'
			SET @Return = 1
		END
	IF NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAND] = @MaGVQL)
		BEGIN
			PRINT N'MA GVQL KHONG TON TAI'
			SET @Return = 2
		END
	UPDATE [NGUOIDUNG] SET MAGVQL = @MaGVQL  WHERE [MAND] = @MaND
	SET @Return = 0
	END TRY
	BEGIN CATCH
		PRINT N'LOI HE THONG'
		ROLLBACK TRAN
		SET @Return = 3
	END CATCH
COMMIT TRAN
GO