CREATE PROC sp_XoaBoMon
@MaBM bigint
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS(SELECT * FROM BOMON WHERE [MABM] = @MaBM)
			BEGIN
				PRINT N'MA BO MON KHONG TON TAI'
				RETURN 1
			END
		DELETE BOMON WHERE [MABM] = @MaBM
	END TRY
	BEGIN CATCH
		PRINT N'LOI HE THONG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO