CREATE PROC [dbo].[sp_CapNhatThongTin]
@MaND bigint,
@HoTen nvarchar(255),
@TenDangNhap varchar(30),
@ToanQuyenGV bit,
@TrangThai bit,
@MaLoai bigint,
@MaBM bigint,
@MaGVQL bigint,
@Return int out
AS
SET TRAN ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
	BEGIN TRY
		SET @Return = -1;
		IF NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAND] = @MaND)
			BEGIN
				PRINT N'MA NGUOI DUNG KHONG TON TAI'
				SET @Return = 1
			END
		ELSE IF NOT EXISTS(SELECT * FROM LOAINGUOIDUNG WHERE [MALOAI] = @MaLoai)
			BEGIN
				PRINT N'MA lOAI NGUOI DUNG KHONG TON TAI'
				SET @Return = 2
			END
		ELSE IF NOT EXISTS(SELECT * FROM BOMON WHERE [MABM] = @MaBM)
			BEGIN
				PRINT N'MA BO MON KHONG TON TAI'
				SET @Return = 3
			END
		WAITFOR DELAY '00:00:05'
		IF @Return = -1
			BEGIN
				UPDATE [NGUOIDUNG] SET TENDANGNHAP = @TenDangNhap,HOTEN = @HoTen, TRANGTHAI = @TrangThai, TOANQUYENGV = @ToanQuyenGV, MALOAI = @MaLoai, MABM = @MaBM, MAGVQL = @MaGVQL  WHERE [MAND] = @MaND
				SET @Return = 0;
			END
	END TRY
	BEGIN CATCH
		PRINT ERROR_MESSAGE()
		SET @Return = 4
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN

CREATE PROC [dbo].[sp_XoaTaiKhoan]
@MaND bigint
AS
SET TRAN ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS(SELECT * FROM NGUOIDUNG WHERE [MAND] = @MaND)
			BEGIN
				PRINT N'MA NGUOI DUNG KHONG TON TAI'
				ROLLBACK TRAN
				RETURN 1
			END
		DELETE [NGUOIDUNG] WHERE [MAND] = @MaND
	END TRY
	BEGIN CATCH
		PRINT ERROR_MESSAGE()
		ROLLBACK TRAN
		RETURN 1
	END CATCH
RETURN 0
COMMIT TRAN
